# Generated by Django 3.2.9 on 2021-11-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_reg_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='profile',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
