<<<<<<< HEAD
# Generated by Django 3.2.9 on 2021-11-30 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_extra_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='extra_data',
        ),
    ]
=======
# Generated by Django 3.2.9 on 2021-11-30 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_extra_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='extra_data',
        ),
    ]
>>>>>>> 4dfdc7fcbba1fb6c58b2f2ad419064b3e21c7d5d
