# Generated by Django 3.2.9 on 2021-12-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_extra_data_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reg',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='reg',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='reg',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='reg',
            name='lastName',
            field=models.CharField(default='mo', max_length=100),
            preserve_default=False,
        ),
    ]
