# Generated by Django 3.2.9 on 2021-12-03 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20211203_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reg',
            name='lastName',
        ),
    ]
