# Generated by Django 3.2.9 on 2021-12-03 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_reg_lastname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reg',
        ),
    ]
