# Generated by Django 3.2.9 on 2021-12-03 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_reg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reg',
        ),
    ]
