# Generated by Django 3.2.9 on 2021-12-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_reg_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='profile',
            field=models.ImageField(upload_to='static/accounts/images/'),
        ),
    ]
