# Generated by Django 3.2.9 on 2021-12-05 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_reg_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reg',
        ),
    ]
