# Generated by Django 3.2.9 on 2021-12-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='password',
            field=models.CharField(default=None, max_length=80),
        ),
    ]
