# Generated by Django 3.2.9 on 2021-12-05 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_reg_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reg',
        ),
    ]
