# Generated by Django 3.2.9 on 2021-11-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('category', models.CharField(choices=[('charity', 'char'), ('orphans', 'or')], max_length=50)),
                ('images', models.ImageField(upload_to='static/images/')),
                ('totalTarget', models.IntegerField()),
                ('tags', models.CharField(max_length=200)),
            ],
        ),
    ]
