# Generated by Django 3.2.9 on 2021-11-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projects_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimages',
            name='image',
            field=models.ImageField(upload_to='projects/images/'),
        ),
    ]
