# Generated by Django 3.2.9 on 2021-11-28 19:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0016_rename_user_id_projectrating_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='projectrating',
            unique_together={('project', 'user_id')},
        ),
    ]
