# Generated by Django 3.2.9 on 2021-11-24 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20211124_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttags',
            name='project',
        ),
        migrations.DeleteModel(
            name='ProjectImages',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.DeleteModel(
            name='ProjectTags',
        ),
    ]
