# Generated by Django 3.2.9 on 2021-11-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectimages_projects_projecttags'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
