# Generated by Django 3.2.9 on 2021-11-26 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_rename_donatins_projects_donations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttags',
            name='project',
        ),
        migrations.DeleteModel(
            name='ProjectImages',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.DeleteModel(
            name='ProjectTags',
        ),
    ]
