# Generated by Django 3.2.9 on 2021-11-26 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0010_auto_20211126_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('category', models.CharField(choices=[('charity', 'charity'), ('Technology', 'Technology'), ('Industrial', 'Industrial')], max_length=50)),
                ('totalTarget', models.IntegerField()),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('rating', models.IntegerField(default=0)),
                ('donations', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projects')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/images/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projects')),
            ],
        ),
    ]
