# Generated by Django 3.2.9 on 2021-11-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_projectimages_projects_projecttags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimages',
            name='image',
            field=models.ImageField(upload_to='static/projects/images/'),
        ),
    ]
