# Generated by Django 3.2.9 on 2021-11-30 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_comments_replies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimages',
            name='project',
        ),
        migrations.AlterUniqueTogether(
            name='projectrating',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='projectrating',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectrating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='user',
        ),
        migrations.RemoveField(
            model_name='projecttags',
            name='project',
        ),
        migrations.RemoveField(
            model_name='replies',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='replies',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='ProjectImages',
        ),
        migrations.DeleteModel(
            name='ProjectRating',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.DeleteModel(
            name='ProjectTags',
        ),
        migrations.DeleteModel(
            name='Replies',
        ),
    ]
