# Generated by Django 3.2.9 on 2021-11-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
